# ---------------- #
#   Main Configs   #
# ---------------- #
baseurl:
url:
date_format: "ordinal"
title: 刘帅Java工程师
subtitle: "你只管努力，剩下的交给给天意！！！"
description: "刘帅的个人博客"
keywords: liuCoding,java
timezone: Asia/Shenzhen
encoding: "utf-8"
side_bar_repo_limit: 5

# ---------------- #
#      Author      #
# ---------------- #
author: 刘帅
organization: 
organization_url: 
github_username: liusCoding
location: Shenzhen, China
email: 14786469221@163.com

# ---------------- #
#    Navigation    #
# ---------------- #
navs:
  -
    href: /
    label: 首页

  -
    href: /categories/
    label: 分类

#   -
#     href: /archives/
#     label: 归档

  -
    href: /wiki/
    label: 维基

  -
    href: /links/
    label: 链接

  -
    href: /about/
    label: 关于

# ---------------- #
#       RSS        #
# ---------------- #
subscribe_rss: /feed.xml

# ---------------- #
#      Jekyll      #
# ---------------- #
markdown: kramdown
kramdown:
    input: GFM
highlighter: rouge
paginate: 10
lsi: false
quiet: false
excerpt_separator: "\n\n"
permalink: /:year/:month/:day/:title/
gems:
    - jekyll-github-metadata
    - rouge
#     - jekyll-html-pipeline
    - jekyll-paginate
    - jekyll-sitemap
    - jekyll-feed
    - jemoji
#     - jekyll-mentions
collections:
    wiki:
        output: true
        permalink: /wiki/:path/

repository: liusCoding/liusCoding.github.io

# ---------------- #
#      Comments    #
# ---------------- #
# support provider: disqus, gitment, gitalk
comments_provider: gitalk
# !!!重要!!! 请修改下面这些信息为你自己申请的
# !!!Important!!! Please modify infos below to yours
# https://disqus.com
disqus:
   username:
## https://imsun.net/posts/gitment-introduction/
gitment:
    owner: liusCoding
    repo: blog-comments
    oauth:
        client_id: d2e1cbbd298958076462
        client_secret: d2e1cbbd298958076462
# https://github.com/gitalk/gitalk#install
gitalk:
    owner: liusCoding
    repo: blog-comments
    clientID: 901e6964484b305c0537
    clientSecret: d6b2140ffb89a65033ddc5e7e120f4161a6dd706
# 在使用其它评论组件时可点击显示 Disqus
lazy_load_disqus : false

# ---------------- #
#      Search      #
# ---------------- #
simple_jekyll_search:
    # 是否支持全文搜索
    fulltext: false
    # 最多显示多少条搜索结果
    limit: 10

# ---------------- #
#    Analytics     #
# ---------------- #
google:
    analytics_id: UA-80669434-1
